---
output: html_document
editor_options: 
  chunk_output_type: console
---
# importing the library

```{r}
library(MASS)
library(biotools)
library(candisc)
library(ROSE)
library(ggplot2)

```


# Importing the data and clean the worksapce

```{r}
# Clear plots
if(!is.null(dev.list())) dev.off()

# Clean workspace
rm(list=ls())

data <- read.table("2.Bank_India_preprocessed_data.csv",header=T, stringsAsFactors=TRUE, sep=",")

```

# Reviewing our dataset

```{r}
summary(data)
# Here we can see the output of the PCA 

# Pick those numerical features
numeriques <- which(sapply(data,is.numeric))
# We don't include id for the analysis
numeriques = numeriques[-1]
dcon <- data[,c(2,numeriques)]

# As in the previous reported mentioned, our dataset are unbalanced
table(dcon$target)
# There are 4572 payed observation, while only 427 overdue are observed.
# The overdue sample only weight 8,5% among the total observation.
```

# Treatement of unbalanced data

```{r}
# We will undersampling our dataset to 854 record, then the observation will be equivalent

data_under_balanced <- ovun.sample(target ~ ., dcon, method = "under", N = 854, seed = 1)$data
summary(data_under_balanced)

```


```{r}
# Let's check the first model with all the numerical variables included.
target.lda_under = lda(target~., data = data_under_balanced); target.lda_under

# It only return LD1, as there is only two group of result, paid or overdue.
```


```{r}
# With the well built, we can apply it to the original dataset.
predict.lda_under = predict(target.lda_under, dcon)
summary(predict.lda_under)

# Let's add the LDA1 component to the dataset and rename the column.
dcon[,10] = predict.lda_under$x[,1]
names(dcon)[10] = "LDA1"


# Check if if its normal. and covariance, and check distribution of balance and unbalance data.
```

# Validation of LDA model

```{r}
# At below, we can plot the distribution over the 1-D histogram.
par(mar=c(3,2.5,1.5,1))

ldahist(data = dcon[,10], g = dcon$target,ymax = 1)

# As we can observe, the variance between clusters are not significant.
```


```{r}
# Confusion matrix

predictions = predict(object = target.lda_under, newdata = dcon[,-1])

CM = table(dcon$target, predictions$class, dnn = c("Actual Class", "Predicted Class")); CM

# At below table, we can observe that the prediction model is not accurate to classify the record.
```

             Predicted Class
Actual Class payed overdue
     overdue   140     287
     payed    2485    2087

```{r}
# And the Accuracy reached is only about 44%.

accuracy = sum(diag(CM))/dim(dcon)[1]*100; accuracy

# and checking the ROC curve, the performance is unsatisfactory.

roc.curve(dcon$target, predictions$class)
```


# Another approach is to combine the under-sampling with generation of artificial data

```{r}

data_both_balanced = ovun.sample(target ~ ., dcon, method = "both", p=0.5, N = 2000, seed = 1)$data

target.lda_both = lda(target~., data = data_both_balanced);

predictions = predict(object = target.lda_both, newdata = dcon[,-1])

CM = table(dcon$target, predictions$class, dnn = c("Actual Class", "Predicted Class")); CM

roc.curve(dcon$target, predictions$class)

```

